[book]
authors = ["Moritz Scheuerle"]
language = "en"
multilingual = false
src = "src"
title = "UNDER CONSTRUCTION"

[output.html]
preferred-dark-theme = "coal"

[output.html.print]
enable = false    

[output.html.search]
enable = false    